runtime: php83

env_variables:
  # Environment variables
  APP_LOG: errorlog
  APP_KEY: base64:uAbPOgKQ6dGnEch2n6Rl4Wk08ZVr41YWZbq0dSnxgO8=
  STORAGE_DIR: /tmp
  DB_DATABASE: project-connect
  DB_USERNAME: root
  DB_PASSWORD: 4b5&m8@nG&k!eFJr
  DB_SOCKET: "/cloudsql/project-connect-409018:europe-west1:project-connect"

beta_settings:
  # For Cloud SQL
  cloud_sql_instances: project-connect-409018:europe-west1:project-connect
