image: php:8.2

pipelines:
  default:
    - step:
        name: 'Build and Test'
        script:
          - echo "Replace this with your build and test script..."
    - step:
        name: 'Lint'
        script:
          - echo "Replace this with your linting script..."
    - step:
        name: 'Security scan'
        script:
          - echo "Replace this with your security scan script..."
    - step:
        name: Deploy to Google App Engine
        script:
          - apt-get update
          - apt-get install -y composer nodejs npm
          - npm install
          - npm run build  # Update this if needed
          - composer install --no-dev --optimize-autoloader
          - pipe: atlassian/google-app-engine-deploy:0.2.1
            variables:
              KEY_FILE: $KEY_FILE  # Make sure this is set in your repo's environment variables
              PROJECT: 'project-connect-409018'  # Replace with your actual project ID
              DEPLOYABLES: 'app.yaml'
