image: php:8.2

pipelines:
  default:
    - step:
        name: 'Build and Test'
        script:
          - echo "Replace this with your build and test script..."
    - step:
        name: 'Lint'
        script:
          - echo "Replace this with your linting script..."
    - step:
        name: 'Security scan'
        script:
          - echo "Replace this with your security scan script..."
    - step:
        name: Deploy to Google App Engine
        script:
          - apt-get update
          # Install specific Composer version
          - curl -sS https://getcomposer.org/installer | php -- --version=2.6.6
          - mv composer.phar /usr/local/bin/composer
          # Install specific Node.js and npm versions using NVM
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          - export NVM_DIR="$HOME/.nvm"
          - source "$NVM_DIR/nvm.sh"
          - nvm install v18.17.1
          - nvm use v18.17.1
          - npm install -g npm@10.2.5
          - npm install
          - npm run build
          - composer install --no-dev --optimize-autoloader
          - pipe: atlassian/google-app-engine-deploy:0.2.1
            variables:
              KEY_FILE: $KEY_FILE
              PROJECT: 'project-connect-409018'
              DEPLOYABLES: 'app.yaml'